function Hd = hilbert_filter
%HILBERT_FILTER Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 9.0 and the Signal Processing Toolbox 7.2.
% Generated on: 26-Feb-2019 16:08:10

% Equiripple Hilbert transformer filter designed using the FIRPM function.

% All frequency values are normalized to 1.

N = 10;           % Order
F = [0.05 0.95];  % Frequency Vector
A = [1 1];        % Amplitude Vector
W = 1;            % Weight Vector

b  = firpm(N, F, A, W, 'hilbert');
Hd = dfilt.dffir(b);

% [EOF]
