#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2017.4 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Tue Oct 16 12:45:08 CEST 2018
# SW Build 2086221 on Fri Dec 15 20:54:30 MST 2017
#
# Copyright 1986-2017 Xilinx, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
ExecStep()
{
"$@"
RETVAL=$?
if [ $RETVAL -ne 0 ]
then
exit $RETVAL
fi
}
ExecStep xsim modulo_fft_tb_behav -key {Behavioral:sim_1:Functional:modulo_fft_tb} -tclbatch modulo_fft_tb.tcl -view /home/joterom/workspace/OctaveSax/Vivado/prueba_FFT/modulo_fft_tb_behav.wcfg -log simulate.log
