# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/joterom/workspace/OctaveSax/Vivado/octave_main/octave_main.srcs/sources_1/ip/ram_memory/ram_memory.xci
# IP: The module: 'ram_memory' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/joterom/workspace/OctaveSax/Vivado/octave_main/octave_main.srcs/sources_1/ip/ram_memory/ram_memory_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ram_memory'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: /home/joterom/workspace/OctaveSax/Vivado/octave_main/octave_main.srcs/sources_1/ip/ram_memory/ram_memory.xci
# IP: The module: 'ram_memory' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/joterom/workspace/OctaveSax/Vivado/octave_main/octave_main.srcs/sources_1/ip/ram_memory/ram_memory_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ram_memory'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
