# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/joterom/workspace/OctaveSax/Vivado/octave_main/octave_main.srcs/sources_1/ip/out_long_memo/out_long_memo.xci
# IP: The module: 'out_long_memo' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/joterom/workspace/OctaveSax/Vivado/octave_main/octave_main.srcs/sources_1/ip/out_long_memo/out_long_memo_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'out_long_memo'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: /home/joterom/workspace/OctaveSax/Vivado/octave_main/octave_main.srcs/sources_1/ip/out_long_memo/out_long_memo.xci
# IP: The module: 'out_long_memo' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/joterom/workspace/OctaveSax/Vivado/octave_main/octave_main.srcs/sources_1/ip/out_long_memo/out_long_memo_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'out_long_memo'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
