# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/Downloads/Nexys4DDR_Master.xdc

# IP: ip/clock_change/clock_change.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==clock_change || ORIG_REF_NAME==clock_change}]
