# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/Downloads/Nexys4DDR_Master.xdc

# IP: ip/ram_memo/ram_memo.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ram_memo || ORIG_REF_NAME==ram_memo} -quiet] -quiet
