# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/UNI/TFG/OctaveSax/Vivado/prueba_FFT/prueba_FFT.srcs/sources_1/ip/comp_fft/comp_fft.xci
# IP: The module: 'comp_fft' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/UNI/TFG/OctaveSax/Vivado/prueba_FFT/prueba_FFT.srcs/sources_1/ip/comp_fft/comp_fft_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'comp_fft'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# IP: D:/UNI/TFG/OctaveSax/Vivado/prueba_FFT/prueba_FFT.srcs/sources_1/ip/comp_fft/comp_fft.xci
# IP: The module: 'comp_fft' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/UNI/TFG/OctaveSax/Vivado/prueba_FFT/prueba_FFT.srcs/sources_1/ip/comp_fft/comp_fft_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'comp_fft'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
