# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/UNI/TFG/octave_main/octave_main.srcs/sources_1/ip/clock_change/clock_change.xci
# IP: The module: 'clock_change' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/UNI/TFG/octave_main/octave_main.srcs/sources_1/ip/clock_change/clock_change_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clock_change'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: d:/UNI/TFG/octave_main/octave_main.srcs/sources_1/ip/clock_change/clock_change.xdc
# XDC: The top module name and the constraint reference have the same name: 'clock_change'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: d:/UNI/TFG/octave_main/octave_main.srcs/sources_1/ip/clock_change/clock_change_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clock_change'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# IP: d:/UNI/TFG/octave_main/octave_main.srcs/sources_1/ip/clock_change/clock_change.xci
# IP: The module: 'clock_change' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/UNI/TFG/octave_main/octave_main.srcs/sources_1/ip/clock_change/clock_change_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clock_change'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: d:/UNI/TFG/octave_main/octave_main.srcs/sources_1/ip/clock_change/clock_change.xdc
# XDC: The top module name and the constraint reference have the same name: 'clock_change'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: d:/UNI/TFG/octave_main/octave_main.srcs/sources_1/ip/clock_change/clock_change_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clock_change'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]
