# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/UNI/TFG/OctaveSax/Vivado/octave_main/octave_main.srcs/sources_1/ip/FFT_transform/FFT_transform.xci
# IP: The module: 'FFT_transform' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/UNI/TFG/OctaveSax/Vivado/octave_main/octave_main.srcs/sources_1/ip/FFT_transform/FFT_transform_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'FFT_transform'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: d:/UNI/TFG/OctaveSax/Vivado/octave_main/octave_main.srcs/sources_1/ip/FFT_transform/FFT_transform.xci
# IP: The module: 'FFT_transform' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/UNI/TFG/OctaveSax/Vivado/octave_main/octave_main.srcs/sources_1/ip/FFT_transform/FFT_transform_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'FFT_transform'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
