webtalk_init -webtalk_dir /home/joterom/workspace/OctaveSax/Vivado/prueba_FFT/prueba_FFT.sim/sim_1/behav/xsim/xsim.dir/modulo_fft_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Wed Oct 10 19:16:21 2018" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2017.4 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2086221" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "ffc6088e-ca4e-4a72-8e93-eb8ab6a9233c" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "0b3d94d2f7334ceb946b568245da8f9e" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "62" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Ubuntu" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Ubuntu 18.04.1 LTS" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel Xeon E3-12xx v2 (Ivy Bridge)" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3702.184 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "2" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "4.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "7 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "4" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.15_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "132064_KB" -context "xsim\\usage"
webtalk_transmit -clientid 87399023 -regid "" -xml /home/joterom/workspace/OctaveSax/Vivado/prueba_FFT/prueba_FFT.sim/sim_1/behav/xsim/xsim.dir/modulo_fft_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html /home/joterom/workspace/OctaveSax/Vivado/prueba_FFT/prueba_FFT.sim/sim_1/behav/xsim/xsim.dir/modulo_fft_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm /home/joterom/workspace/OctaveSax/Vivado/prueba_FFT/prueba_FFT.sim/sim_1/behav/xsim/xsim.dir/modulo_fft_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
