# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/UNI/TFG/octave_main/octave_main.srcs/sources_1/ip/fft_module/fft_module.xci
# IP: The module: 'fft_module' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/UNI/TFG/octave_main/octave_main.srcs/sources_1/ip/fft_module/fft_module_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fft_module'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# IP: D:/UNI/TFG/octave_main/octave_main.srcs/sources_1/ip/fft_module/fft_module.xci
# IP: The module: 'fft_module' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/UNI/TFG/octave_main/octave_main.srcs/sources_1/ip/fft_module/fft_module_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fft_module'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
